services:
  unit_test:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/unit_test"
      - "/opt/unit_test/node_modules"
    environment:
      - NEXT_WEBPACK_USEPOLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true